apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ci
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  test:
    steps:
      - name: Checkout source from AZDO repo
        uses: cb-demos/azdo-scm-checkout@v1
        with:
          org-name: ${{ vars.AZDO_ORG }}
          repo-name: ${{ vars.REPO_NAME }}
          project-name: ${{ vars.PROJECT_NAME }}
          access-token: ${{ secrets.AZURE_PERSONAL_ACCESS_TOKEN }}
      - name: Run unit tests
        id: unit-tests
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn test -Dspring-javaformat.validate.skip=true
      - uses: cloudbees-io/publish-test-results@v1
        kind: test
        with:
          test-type: JUnit
          folder-name: /cloudbees/workspace/target/surefire-reports/*.xml
  package:
    steps:
      - name: Checkout source from AZDO repo
        uses: cb-demos/azdo-scm-checkout@v1
        with:
          org-name: ${{ vars.AZDO_ORG }}
          repo-name: ${{ vars.REPO_NAME }}
          project-name: ${{ vars.PROJECT_NAME }}
          access-token: ${{ secrets.AZURE_PERSONAL_ACCESS_TOKEN }}
      - name: Configure container registry credentials
        id: dockerconfig
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        id: unit-tests
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn package -Dspring-javaformat.validate.skip=true
      - uses: cloudbees-io/kaniko@v1
        name: Build and push docker image
        kind: build
        with:
          destination: ${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic:${{ cloudbees.scm.sha }},${{ secrets.DOCKERHUB_USERNAME }}/springpet-clinic:latest
          tar-path: container-image.tar
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
#      - uses: cloudbees-io/register-build-artifact@v1
#        with:
#          name: spring-petclinic
#          version: ${{ cloudbees.scm.sha }}
#          url: "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic:${{ cloudbees.scm.sha }}"
      - id: upload-binary
        name: Upload binary using action
        uses: cloudbees-io/asset-chain-utils/upload-binary@v1
        with:
          file-path: container-image.tar
          file-type: BINARY_CONTAINER
    needs:
      - test
