apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ci
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  test:
    steps:
      - name: Checkout source from AZDO repo
        uses: cb-demos/azdo-scm-checkout@v1
        with:
          org-name: ${{ vars.AZDO_ORG }}
          repo-name: ${{ vars.REPO_NAME }}
          project-name: ${{ vars.PROJECT_NAME }}
          access-token: ${{ secrets.AZURE_PERSONAL_ACCESS_TOKEN }}
      - name: Run unit tests
        id: unit-tests
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn test -Dspring-javaformat.validate.skip=true
      - uses: cloudbees-io/publish-test-results@v1
        kind: test
        with:
          test-type: JUnit
          folder-name: /cloudbees/workspace/target/surefire-reports/*.xml
